export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const LOAD_QUESTIONS_ERROR = 'LOAD_QUESTIONS_ERROR';

export const LOAD_PARTS_SUCCESS = 'LOAD_PARTS_SUCCESS';
export const LOAD_PARTS_ERROR = 'LOAD_PARTS_ERROR';

export const LOAD_PART = 'LOAD_PART';

export const UPDATE_TEXT_SUCCESS = 'UPDATE_TEXT_SUCCESS';
export const UPDATE_TEXT_ERROR = 'UPDATE_TEXT_ERROR';

export const LOAD_SUGGESTIONS_SUCCESS = 'LOAD_SUGGESTIONS_SUCCESS';
export const LOAD_SUGGESTIONS_ERROR = 'LOAD_SUGGESTIONS_ERROR';
