export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const LOAD_QUESTIONS_ERROR = 'LOAD_QUESTIONS_ERROR';
export const LOAD_PARTS_SUCCESS = 'LOAD_PARTS_SUCCESS';
export const LOAD_PARTS_ERROR = 'LOAD_PARTS_ERROR';
